__all__ = ["findBin",
           "findLib",
           "findConf",
           "findData",
           "listData",
           "confPaths",
           "dataPaths",
           "binPaths",
           "libPaths",
           "setWritablePath",
           "userWritableDataPath",
           "userWritableConfPath",
           "sdkPrefix"]
